### ISSUE TITLE
Proper Credit not given to contributers

### ISSUE THREAD

**Issue by ashawe** [chaitanyarahalkar/Cyberfort-CTF-Website#5]
As far as I can see, the front end of this website is taken from ashawe's [CTF-Website-Template-2020](https://github.com/ashawe/CTF-Website-Template-2019)

There is no mention of this anywhere. 
It would be better if credits were given to people who worked on this project. No offense
Thanks.

**Comment by chaitanyarahalkar** [comment]
Before you can ask for credits, make sure you add a license to your repository! A repository without a license is under no legal bindings. 

Anyway, credit due is credit given. README has been updated! 

Cheers.

**Comment by ashawe** [comment]
Technically a repository without a license is considered under the author's exclusive copyright. In general, that means nobody else can use, copy, distribute, or modify that work without being at risk of take-downs, shake-downs, or litigation. More about it [here](https://opensource.guide/legal/#why-do-people-care-so-much-about-the-legal-side-of-open-source).

Also, after our discussion, I updated the LICENSE of my code to give you permission to use it. But that license is GPLv2 which has some conditions you aren't adhering to. So you can't change the license to MIT which you've done. Anyway, make sure you ask the owners of the code to add a LICENSE before you use their code.
